# Programa Ingenias+ Data Science

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
import numpy as np

# 1. Crear un arreglo de ceros de longitud 12.
EJ1 = np.zeros(12)
print ("EJERCICIO 1\n", EJ1)

# 2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5.
EJ2 = np.zeros(12)
EJ2[4]=10
print("EJERCICIO 2\n", EJ2)

# 3. Crear un arregle que tenga los números del 10 al 49.
EJ3 = np.arange(10, 50)
print("EJERCICIO 3\n", EJ3)

# 4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
EJ4 = np.arange(9).reshape(3, 3)
print("EJERCICIO 4\n", EJ4)

# 5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
EJ5 = (np.random.rand(100))
print("EJERCICIO 5\n", EJ5)
print("EJERCICIO 5 - MEDIA\n", np.mean(EJ5))
print("EJERCICIO 5 - VARIANZA\n", np.var(EJ5))

# 6. Calcular la media de un arreglo usando np.sum
EJ6 = media_sum = np.sum(EJ5)/ len(EJ5)
print("EJERCICIO 6 - MEDIA CON NP.SUM\n", EJ6)

# 7. Calcular la varianza de un arreglo usando np.sum y np.mean
MEDIA_EJ5 = np.mean(EJ5)
CALCULO_VARIANZA = np.sum((EJ5 - MEDIA_EJ5) ** 2) / len(EJ5)
print("EJERCICIO 7 - CALCULO VARIANZA \n", CALCULO_VARIANZA)

# 8. Crear un array de números aleatorios usando np.random.randn.
EJ8 = np.random.randn(15)
print("EJERCICIO 8\n", EJ8)




EJERCICIO 1
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
EJERCICIO 2
 [ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.]
EJERCICIO 3
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
EJERCICIO 4
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
EJERCICIO 5
 [0.34521964 0.41227132 0.23589647 0.75420706 0.74977865 0.59624215
 0.90892769 0.32569629 0.46992644 0.15675731 0.89425527 0.49913946
 0.47517425 0.04563219 0.12203803 0.63856059 0.97983259 0.24408257
 0.48933097 0.54836406 0.45253683 0.69217201 0.0220601  0.1819429
 0.70388966 0.96823717 0.83424132 0.92245726 0.35896019 0.49675798
 0.84077281 0.20425272 0.53458502 0.67748139 0.91154528 0.47785377
 0.069143   0.59054729 0.579005   0.95680131 0.03018827 0.37108229
 0.04414473 0.54663349 0.88258098 0.95905527 0.59429904 0.44882944
 0.97530762 0.82573921 0.31799188 0.80429076 0.81420713 0.53675166
 0.33920793 0.74617845 0.10094142 0.89423033 0.57107665 0.21754079
 0.33910084 0.02741455 0.65